### ISSUE TITLE
(sharing)елементы раздела услуг налазят друг на друга (severity:medium ,priority:normal) 

### ISSUE THREAD

**Issue by Tolstaya** [TheAwesomeCompany/Bumperball#10]
экран 1360*768
браузер Mozilla версия 45, Chrome 49
reproducibility: всегда
description:елементы раздела услуг налазят друг на друга
expected result : елементы раздела услуг налазят друг на друга
actual result :елементы раздела услуг налазят друг на друга
steps to reproduce: зайти на сайт http://active.kh.ua

**Comment by kulik** [comment]
Please attach screensot

**Comment by kulik** [comment]
not well formed issue
