### ISSUE TITLE
Переход на страницу сайта в соцсети осуществляется в той же вкладке

### ISSUE THREAD

**Issue by dmitryklimenko** [TheAwesomeCompany/Bumperball#11]
Browser: Google Chrome 49.0
Version: 1.0

Description:
При переходе на страницу "Бампербола" в соцсети ВКонтакте, Instagram и Facebook новая страница открывается в той же вкладке. 
Actual Result: Страница "Бампербола" в соцсети открывается в той же вкладке
Expection Result: Страница "Бампербола" в соцсети открывается в новой вкладке
STR: 
1). Открыть сайт http://active.kh.ua/
2). Нажать на иконку сайта ВКонтакте

**Comment by kulik** [comment]
fixed
