### ISSUE TITLE
(sharing)при переходе по ссылкам меню ,меню-бар перекрывает верхнюю часть блока(severity:medium ,priority:normal)

### ISSUE THREAD

**Issue by Tolstaya** [TheAwesomeCompany/Bumperball#12]
экран 1360*768
браузер Mozilla версия 45, Chrome 49
reproducibility: всегда
description:при переходе по ссылкам меню ,меню-бар перекрывает верхнюю часть блока
expected result : при переходе по ссылкам меню ,меню-бар не перекрывает верхнюю часть блока
actual result :при переходе по ссылкам меню ,меню-бар перекрывает верхнюю часть блока
steps to reproduce: 
1.зайти на сайт http://active.kh.ua
2. перейти по ссылке на карта площадок

**Comment by kulik** [comment]
fixed
