### ISSUE TITLE
Разные отступы в полях ввода при оформлении заявки

### ISSUE THREAD

**Issue by dmitryklimenko** [TheAwesomeCompany/Bumperball#13]
Browser: Google Chrome 49.0
Version: 1.0

Description:
Когда мы оформляем заявку, в поле ввода дополнительной информации присутствует слишком большой отступ между нижней строкой и нижней линией поля ввода. 
Actual Result: Присутствует большой отступ в поле ввода дополнительной информации
Expection Result: Ни в одном из полей не больших отступов
STR: 
1). Открыть сайт http://active.kh.ua/
2). Нажать "Играть в Бампербол"
3). Ввести в поле ввода телефона номер 093-234-11-45
4). Ввести в поле ввода дополнительной информации "Нас будет 12 человек"

Comments: https://screencloud.net/v/Umu

**Comment by kulik** [comment]
not a bug
