### ISSUE TITLE
(navigation bar) Слово "Бампербол" накладывается на другое слово; Важность - средняя; Срочность - нормальная; Косметический дефект;

### ISSUE THREAD

**Issue by oskar41** [TheAwesomeCompany/Bumperball#15]
Version: 1.0
Device: Ubuntu, mozilla firefox v.45, resolution 1366x768
Steps: 
1)Open http://active.kh.ua
act.res: bad label position, terrible readability
exp.res: label clearly visible

**Comment by kulik** [comment]
#18
