### ISSUE TITLE
(navigation bar) номера телефона на кнопке телефона видны только после наведения на них курсора важность:средняя, срочность:нормальная; симптомы:косметический дефект

### ISSUE THREAD

**Issue by oskar41** [TheAwesomeCompany/Bumperball#17]
Version: 1.0
Device: Ubuntu, mozilla firefox v.45, resolution 1366x768
Steps: 
1)Open http://active.kh.ua
2)Click "phone" button
3)Place the cursor on the number
act.res: terrible number readability
exp.res: number clearly visible

**Comment by kulik** [comment]
fixed
