### ISSUE TITLE
(Меню навигации) Перекрывание пункта "Контакты" пунктом "Бампербол" (major; high)

### ISSUE THREAD

**Issue by Sergey-Saprikin** [TheAwesomeCompany/Bumperball#18]
В меню навигации пункт "Бампербол" перекрывает "Контакты"
_всегда_ (workaround: yes)
Version: (1.0)
Device: ноутбук (15:6; 1366 х 768)
Браузер: хром (48)
Steps: 
1) Открыть сайт: http://active.kh.ua
2) Посмотреть на меню навигации
Expected result: пункт "Бампербол" перекрывает "Контакты"
Actuale result: пункт "Бампербол"  не перекрывает "Контакты"
Symptom: cosmetic flaw
Comments: На другом разрешении пункты не перекрываются

**Comment by kulik** [comment]
resolved
