### ISSUE TITLE
Navigation bar. Ссылки на социальные сети делают переход в этой же вкладке. (minor/low)

### ISSUE THREAD

**Issue by alino44ka** [TheAwesomeCompany/Bumperball#19]
В меню при переходе на любую из ссылок социальной сети, сайт открывается в этой же вкладке.

Version: 1.0
Device: браузер Chrome (48)
Steps: 
- открыть сайт http://active.kh.ua/#
- нажать на значок Vkontakte

Expected result: При нажатии на значок социальной сети, переход осуществляется в новой вкладке
Actual result: При нажатии на значок социальной сети, переход осуществляется в текущей вкладке

**Comment by kulik** [comment]
fixed on all devices
