### ISSUE TITLE
(share bar)  Слово "поделится" залазит за рамки экрана; важность:средняя, срочность:нормальная; симптомы:косметический дефект

### ISSUE THREAD

**Issue by oskar41** [TheAwesomeCompany/Bumperball#20]
Version: 1.0
Device: Ubuntu, mozilla firefox v.45, resolution 1366x768
Steps:
1) Open http://active.kh.ua
2) View share bar on the rigth side of the display
act.res: bad label position
exp.res: label clearly visible

**Comment by kulik** [comment]
Which label there is a lot labels on the page. not enough information

**Comment by kulik** [comment]
3rd paty API
