### ISSUE TITLE
В вернем меню ссылка с названием Бампербол перекрывает ссылку Контакты

### ISSUE THREAD

**Issue by katekharchenko22** [TheAwesomeCompany/Bumperball#21]
Версия сайта: 1.0
ОС: Windows 7
Браузер: Google Chrome, версия 49
Разрешение экрана: 1366х768
Диагональ экрана: 15,6"
Важность: major
Воспроизводимость: всегда

Description:
В вернем меню ссылка с названием Бампербол перекрывает ссылку Контакты, что приводит к ее неработоспособности.
Фактический результат: ссылки наслоены друг на друга.
Ожидаемый результат: ссылки отображаются раздельно, по ним возможен переход.

Steps for reprduce:
1. Открыть сайт http://active.kh.ua/

Симптомы:
косметический дефект

Комментарии:
при изменении разрешения экрана на более низкое или более высокое, ссылки отображаются корректно

**Comment by kulik** [comment]
It is better to describe borders of widthes of screen when it is reproduced. since it is reproduced on screens from 1200 - 1600

**Comment by kulik** [comment]
fixed
