### ISSUE TITLE
(Share bar) Надпись "Поделиться" не видна полностью (minor; low)

### ISSUE THREAD

**Issue by Sergey-Saprikin** [TheAwesomeCompany/Bumperball#22]
В Share bar надпись "Поделиться" не полностью видна
всегда (workaround: no)
Version: (1.0)
Device: ноутбук (15:6; 1366 х 768)
Браузер: хром (48)
Steps: 
1) Открыть сайт: http://active.kh.ua
2) Посмотреть на Share bar 
Expected result: надпись видна частично
Actuale result: надпись видна полностью
Symptom: cosmetic flaw
Attachment:
![111](https://cloud.githubusercontent.com/assets/17886282/13886414/cc90d74a-ed47-11e5-8392-9f2e527d1011.jpg)

**Comment by kulik** [comment]
it is better to add screenshot with rounding what is wrong

**Comment by kulik** [comment]
duplicate, 
3rd paty API won't fix
