### ISSUE TITLE
(в Меню значок Телефонной трубке)Summary  : Неверно написан телефонный номер life(major,normal)

### ISSUE THREAD

**Issue by Valeri1788** [TheAwesomeCompany/Bumperball#24]
#23 Description:

Version:1.0
Browser: Mozilla Firefox 44
В Меню иконка Телефонная трубка неверно указан телефонный номер life.
Expected result- номер life указан 
Actual result - номер life опечатка (073)03 03 441
Steps:
1. Открыть сайт active.kh.ua
2.Навести на иконку Телефонная трубка 
3.Выбрать оператор life
Reproducibility:
всегда

**Comment by kulik** [comment]
Don't understand. What is the mistake. 073 - it is life.do you mean space missed? or maybe that it is written white text on white background? http://screencloud.net/v/tLFn  http://screencloud.net/v/F46I

**Comment by Valeri1788** [comment]
I not right pointed bug, I thought that (073) is a typo, there's only operators (093) and (063) life.
