### ISSUE TITLE
(Меню навигации) Не работает пункт "Бампербол"  (major; high)

### ISSUE THREAD

**Issue by Sergey-Saprikin** [TheAwesomeCompany/Bumperball#25]
При нажатии на пункт "Бампербол" не перходит по ссылке
всегда (workaround: no)
Version: (1.0)
Device: ноутбук (15:6; 1366 х 768)
Браузер: хром (48)
Steps: 
1) Открыть сайт: http://active.kh.ua
2) Посмотреть на меню навигации
Expected result: переходит по ссылке 
Actuale result: не переходит по ссылке 
Symptom: cosmetic flaw; missing feature

**Comment by kulik** [comment]
Please add screenshots with place where you pressing. As i understand this is Home button label. So Since this is just landing page - there is no place where to go.

**Comment by Ksiu-Sliusarova** [comment]
I agree with Sergey. As word Бампербол is situated in one row with other words that are links, and word Бампербол looks almost like other words from the top bar (colour, font, size) a user expects that this word is also a link. He/she clicks wanting to see some general info about this activity (like "What is Бампербол") but nothing happens. So... it can be considered as unexpected behaviour.

**Comment by alino44ka** [comment]
Я предполагаю, что этот пункт Бампербол предназначен для возврата к топ странице. Так же этот пункт предназначен для того, что бы одним кликом мышки открывать сайт в новой вкладке.

**Comment by kulik** [comment]
scroled to top
