### ISSUE TITLE
Punctuation and grammar mistakes in the text (minor; low)

### ISSUE THREAD

**Issue by dmitryklimenko** [TheAwesomeCompany/Bumperball#26]
Browser: Chrome 49.0
Version: 1.0

**Description:**
The text have many punctuation mistakes. In many places there are no commas, no full stop at the end of the proposal, as well as the word "Bamperball" written in Russian and then in English. Mistake in word "Корпоратив"

**Actual Result:** Punctuation mistakes are present
**Expection Result:** Punctuation mistakes are missing
**STR:**
1). Open http://active.kh.ua/

**Attachments:**
http://i11.pixs.ru/storage/4/6/2/1png_1221391_21142462.png
http://i10.pixs.ru/storage/4/6/3/2png_3413311_21142463.png
http://i9.pixs.ru/storage/4/6/6/3png_9367872_21142466.png
http://i10.pixs.ru/storage/4/7/6/4png_4420513_21142476.png
http://i10.pixs.ru/storage/4/8/4/5png_3505544_21142484.png
http://i9.pixs.ru/storage/4/9/0/6png_7176237_21142490.png

**Comment by Ksiu-Sliusarova** [comment]
Согласна. Ошибок в тексте куча. Плюс присутствуют некоторые логические нестыковки. Предложение по улучшению : полностью перечитать и отредактировать текст.

**Comment by kulik** [comment]
fixed all issues that mentioned in screenshots. Bumperball eng/ru - this is SEO stuff...
