### ISSUE TITLE
Блок "Часто задаваемые вопросы". В пункте"Есть ли какие то опасности и ограничения?" Предложение "не рекомендуется играть беременным" начинается с маленькой буквы.(minor,low)

### ISSUE THREAD

**Issue by OlgaGushchina** [TheAwesomeCompany/Bumperball#27]
Блок "Часто задаваемые вопросы". В пункте"Есть ли какие то опасности и ограничения?" Предложение "не рекомендуется играть беременным" начинается с маленькой буквы.
Version: (1.0)
Device: ноутбук ( 1600 х 900)
Браузер: хром (48)
Steps: 
1) Открыть сайт: http://active.kh.ua
2) Посмотреть на меню навигации
Expected result:Предложение "не рекомендуется играть беременным" начинается с большой буквы .
Actuale result:Предложение "не рекомендуется играть беременным" начинается с маленькой буквы. 
Symptom: cosmetic flaw

**Comment by kulik** [comment]
fixed
