### ISSUE TITLE
No confirmation of sending the application (medium, normal)

### ISSUE THREAD

**Issue by dmitryklimenko** [TheAwesomeCompany/Bumperball#28]
Browser: Chrome 49.0
Version: 1.0

**Description:**
After clicking "Играть в Бампербол" window appears in which you should to include your phone\Skype\Viber and additional information. When you input information in both text field, click on the "Отправить заявку" button. For a short time, this button disappears and then appears again. Not clear whether the application has been submitted successfully.

**Actual Result:** After filling out the text fields and sending the application, there is no success message\not successful surgery
**Expection Result:** Appear message with confirmation of sending application.
**STR:** 
1). Open http://active.kh.ua/
2). Click "Играть в Бампербол"
3). Input "096-42-66-234" in first text field
4). Input "Нас будет 20 человек" in second text field
5). Click "Отправить заявку"

**Attachments:**
http://i10.pixs.ru/storage/8/8/5/11png_3359410_21142885.png
http://i9.pixs.ru/storage/8/9/0/22png_4398050_21142890.png

**Comment by kulik** [comment]
fixed
