### ISSUE TITLE
Блок "Где мы проводим игры".Предложение" на карте можно ознакомиться с предложенным выбором площадок, а также выбрать район, и мы договоримся за аренду площадки именно под Вашу игру" начинается с маленькой буквы.(minor,low)

### ISSUE THREAD

**Issue by OlgaGushchina** [TheAwesomeCompany/Bumperball#29]
Блок "Где мы проводим игры".Предложение" на карте можно ознакомиться с предложенным выбором площадок, а также выбрать район, и мы договоримся за аренду площадки именно под Вашу игру" начинается с маленькой буквы.
Version: (1.0)
Device: ноутбук ( 1600 х 900)
Браузер: хром (48)
Steps: 
1) Открыть сайт: http://active.kh.ua
2) Кликнуть карта площадок
Expected result:Предложение" на карте можно ознакомиться с предложенным выбором площадок, а также выбрать район, и мы договоримся за аренду площадки именно под Вашу игру" начинается с большой буквы.
Actuale result:Предложение" на карте можно ознакомиться с предложенным выбором площадок, а также выбрать район, и мы договоримся за аренду площадки именно под Вашу игру" начинается с маленькой буквы.
Symptom: cosmetic flaw

**Comment by kulik** [comment]
magicaly fixed
