### ISSUE TITLE
Incorect position of title in navigation bar (menu)

### ISSUE THREAD

**Issue by dmitryklimenko** [TheAwesomeCompany/Bumperball#3]
Browser: Google Chrome 49.0
Version: 1.0

Description:
При открытии страницы сайта мы видим, что надпись "Бампербол" налазит на надпись "Контакты" в верхнем меню при разрешении экрана 1360х768
Actual Result: Надписи "Бампербол" и "Контакты" сливаются
Expection Result: Надписи "Бампербол" и "Контакты" разделены
STR: 
1). Открыть сайт http://active.kh.ua/

Comments: http://i10.pixs.ru/storage/7/3/6/1png_7767508_21119736.png

**Comment by kulik** [comment]
This is good that you added Screenshot. But it is better to add all width that reproducable

**Comment by kulik** [comment]
fixed
