### ISSUE TITLE
Not specified price and the possibility of game for 1 to 8 people (minor, low)

### ISSUE THREAD

**Issue by dmitryklimenko** [TheAwesomeCompany/Bumperball#30]
Browser: Chrome 49.0
Version: 1.0

**Description:**
When user clicking on the section "Стоимость" in the navigation bar, he move to the information on the cost of the game. There have package "Пакет Друзья", "Пакет Тусовка" and "Корпоратив". The number of participants for each of these packages is increasing respectively with their listing. "Пакет Друзья" can be used for of 8 to 14 people. On the page of the site is not written anywhere minimum number of possible players.

**Actual Result:** Not specified price and the possibility of game for 1 to 8 people.
**Expection Result:** In the description of the game says that not allowed to play to 8 people \ The specified price for play of 2 to 7 people.
**STR:**
1). Open http://active.kh.ua/
2). Click "Стоимость" in the navigation bar

**Attachments:** -

**Comment by kulik** [comment]
Exception Result:  
Expected - not Excetion

Good issue

**Comment by dmitryklimenko** [comment]
Thanks, i edit everywhere

**Comment by kulik** [comment]
minimum 6 person

**Comment by kulik** [comment]
fixed
