### ISSUE TITLE
Блок "Стоимость". Слово "КОРПАРАТИВ" в блоке пакетов. Орфографическая ошибка.(minor,low)

### ISSUE THREAD

**Issue by OlgaGushchina** [TheAwesomeCompany/Bumperball#31]
Блок "Стоимость". Слово "КОРПАРАТИВ" в блоке пакетов. Орфографическая ошибка.
Version: (1.0)
Device: ноутбук ( 1600 х 900)
Браузер: хром (48)
Steps: 
1) Открыть сайт: http://active.kh.ua
2) Кликнуть "Стоимость"
Expected result: КОРПОРАТИВ
Actuale result: КОРПАРАТИВ 
Symptom: cosmetic flaw

**Comment by kulik** [comment]
fixed
