### ISSUE TITLE
Present link with unclear function (minor, low)

### ISSUE THREAD

**Issue by dmitryklimenko** [TheAwesomeCompany/Bumperball#32]
Browser: Chrome 49.0
Version: 1.0

**Description:**
When user directing cursor over the word "Бампербол" in the center of the page, arrow-cursor changes to a pointer-cursor. This means that clicking on a word, the user switches on a given link. But when you click on "Бампербол", nothing happens. I do not understand the function of this link.

**Actual Result:** Present link with unclear function
**Expection Result:** When you hover over the word "Бампербол" cursor does not change, it's just the name of the game.
**STR:**
1). Open http://active.kh.ua/
2). Click "Бампербол" in the navigation bar

**Attachments:** -

**Comment by kulik** [comment]
native behaviour by guidelines
