### ISSUE TITLE
Окно заявки. В поле "Телефон, Скайп, Вайбер, емейл..." можно ввести неограниченное количество символов.(major,normal)

### ISSUE THREAD

**Issue by OlgaGushchina** [TheAwesomeCompany/Bumperball#33]
Окно заявки. В поле "Телефон, Скайп, Вайбер, емейл..." можно ввести неограниченное количество символов.
Version: (1.0)
Device: ноутбук ( 1600 х 900)
Браузер: хром (48)
Steps: 
1) Открыть сайт: http://active.kh.ua
2) Кликнуть "Играть в бампербол"
3)Ввести в поле "Телефон, Скайп, Вайбер, емейл..."-фывапролджжжждлорпавыфывапапрольотрпавывапртоьтрипмампирто
4)Кликнуть "Отправить заявку"
Expected result:"Телефон, Скайп, Вайбер, емейл..." можно ввести до 30 -ти символов 
Actuale result:В поле "Телефон, Скайп, Вайбер, емейл..." можно ввести фывапролджжжждлорпавыфывапапрольотрпавывапртоьтрипмампирто
Symptom: incorrect operation

**Comment by kulik** [comment]
fixed
