### ISSUE TITLE
Окно заявки. Нет окна о подтверждении заявки.(major,high)

### ISSUE THREAD

**Issue by OlgaGushchina** [TheAwesomeCompany/Bumperball#34]
Окно заявки. Нет окна о подтверждении заявки.
Version: (1.0)
Device: ноутбук ( 1600 х 900)
Браузер: хром (48)
Steps: 
1) Открыть сайт: http://active.kh.ua
2) Кликнуть "Играть в бампербол"
3)Ввести в поле "Телефон, Скайп, Вайбер, емейл..."-0506784532
4)Кликнуть "Отправить заявку"
Expected result:Появилось окно"Ваша заявка принята"
Actuale result: Нет окна о подтверждении заявки.
Symptom: incorrect operation

**Comment by kulik** [comment]
magicaly fixed
