### ISSUE TITLE
Окно заявки.Не очищается информация в полях после отправки заявки.(major,high) 

### ISSUE THREAD

**Issue by OlgaGushchina** [TheAwesomeCompany/Bumperball#35]
Окно заявки.После отправления заявки, при повторном открытии окна заявки, остается информация введенная в поля заявки.
Version: (1.0)
Device: ноутбук ( 1600 х 900)
Браузер: хром (48)
Steps: 
1) Открыть сайт: http://active.kh.ua
2) Кликнуть "Играть в бампербол"
3)Ввести в поле "Телефон, Скайп, Вайбер, емейл..."-0506784532
4)Кликнуть "Отправить заявку"
5)Кликнуть "Играть в бампербол"
Expected result:Пустые поля ввода
Actuale result: В поле "Телефон, Скайп, Вайбер, емейл..."-0506784532
Symptom: incorrect operation

**Comment by kulik** [comment]
fixed
