### ISSUE TITLE
Incorrect conditions in the package "Друзья" (medium, normal)

### ISSUE THREAD

**Issue by dmitryklimenko** [TheAwesomeCompany/Bumperball#37]
Browser: Google Chrome 49.0
Version: 1.0

**Description:**
Once a user visited the site and clicked on the "Стоимость", he has movedin the section with a variety of packages and their prices. The package "Друзья" have strange conditions. It says that it can be ordered from 8 to 14 people, price per person per hour is equal to 100 UAH, but below written in brackets, that minimum order - 1000 UAH. Exactly the same situation with the election of two or three hours of play. It turns out that the range of the allowable number of participants in the game for this package is from 10 to 14. Alternatively, the minimum order value must be equal to 800 UAH.

**Actual Result:** The terms of the package "Друзья" contradict themselves
**Expection Result:** The minimum order value for one hour in the package "Friends" is 800 UAH\ Minimum number of people for the use of package "Друзья" is 10 people.
**STR:**
1). Open http://active.kh.ua/
2). Click "Стоимость"

**Attachments:**
https://screencloud.net/v/Fu9K

**Comment by kulik** [comment]
https://github.com/TheAwesomeCompany/Bumperball/issues/39
