### ISSUE TITLE
(Раздел Стоимость/Корпоратив) Некорректная, недружественная для пользователя текстовка в разделе (major, normal)

### ISSUE THREAD

**Issue by Ksiu-Sliusarova** [TheAwesomeCompany/Bumperball#38]
Версия сайта - 1.0
ОС - Windows 7 Максимальная
Браузер - Google Chrome, версия 48.0.2564.116 m
Разрешение экрана - 1366х768

Воспроизводимость - всегда.

Описание: Помимо грамматической ошибки в слове "КорпАратив" вместо "КорпОратив" довольно странно, настойчиво и навязчиво выглядит фраза Свяжитесь с нами аж 4 раза подряд: 60мин Свяжитесь с нами, 120мин Свяжитесь с нами, 240мин Свяжитесь с нами, кнопка СВЯЗАТЬСЯ СЕЙЧАС. К тому же в соседних разделах формат написания времени - 60 минут, а для Корпоратива - 60мин (без пробела и сокращенно), что выглядит не эстетично.

Ожидаемый результат: Нет грамматических ошибок, единообразие формата текста во всех разделах стоимостей, конкретные суммы (например, от .... грн (по договоренности)).

Фактический результат: некорректный и навязчивый блок слов вместо конкретных цен.

Шаги: 
1. Открыть сайт http://active.kh.ua/ 
2. В верхнем меню выбрать раздел Стоимость и посмотреть, как он выглядит.

Симптомы: unfriendly behavior, cosmetic flaw, enhancement.

Предложение по улучшению: прописать 60 минут и т.д. с пробелами и полностью; указать цены от ... грн и в скобочках сделать приписку "стоимость договорная" и внизу оставить только 1 кнопку СВЯЗАТЬСЯ С НАМИ.

**Comment by kulik** [comment]
fixed
