### ISSUE TITLE
Incorrect display on Internet Explorer browser

### ISSUE THREAD

**Issue by dmitryklimenko** [TheAwesomeCompany/Bumperball#4]
Browser:  Internet Explorer 8
Version: 1.0

Description:
При открытии страницы сайтав браузере IE мы видим, что все элементы интерфейса отображены некорректно
Actual Result: Интерфейс сайта некорректно отображается на браузере IE
Expection Result: Интерфейс сайта корректно отображается на браузере IE
STR: 
1). Запустить браузер IE
2). Открыть сайт http://active.kh.ua/

Comments: http://i10.pixs.ru/storage/8/1/5/21png_3667041_21119815.png

**Comment by kulik** [comment]
IE not supported yet...
