### ISSUE TITLE
Does not work move function on the city map (minor, low)

### ISSUE THREAD

**Issue by dmitryklimenko** [TheAwesomeCompany/Bumperball#40]
Browser: Google Chrome 49.0
Version: 1.0

**Description:**
In the section "Где мы проводим игры" have a map of the city, where are marked all the possible area of the games. To zoom the map, you should click on the "+" icon in the lower right corner. However, when the user tries to move area in the approximate mode, nothing happens.

**Actual Result:** Unable to moving on the city map
**Expection Result:** The user can examine in detail any area of the game.
**STR:**
1). Open http://active.kh.ua/
2). Click "Карта площадок"
3). Click on the "+" five times
4). Drag computer mouse

**Attachments:** -

**Comment by kulik** [comment]
good description, but better to say 
drag&drop instead of ( Try to change the location with the computer mouse)
