### ISSUE TITLE
долго грузится сайт (critical,high)

### ISSUE THREAD

**Issue by OlgaGushchina** [TheAwesomeCompany/Bumperball#41]
при открытии сайта ,долго грузится(мин 10 сек) видео.После загрузки видео тормозит (6 сек)
Version: (1.0)
Device: ноутбук ( 1600 х 900)
Браузер: хром (48)
Steps: 
1) Открыть сайт: http://active.kh.ua
Expected result:Сайт быстро загружается,видео не тормозит
Actuale result:сайт загружается мин 10 сек,видео тормозит мин 6 сек
Symptom:slow perfomanse
comments: сделать вместо видео картинку

**Comment by kulik** [comment]
fixed. For mobile added different button play. Resources will be optimized in future
