### ISSUE TITLE
(main bar) не работает функция "отправить заявку";важность:критическая, срочность:высокая; симптомы: нереализованная функциональность; 

### ISSUE THREAD

**Issue by oskar41** [TheAwesomeCompany/Bumperball#42]
Version: 1.0
Device: Windows 10, mozilla firefox v.45, resolution 1280x1024
Steps:
1) Open http://active.kh.ua
2) Нажать кнопку "играть в бампербол"
3) Ввести телефон 380978834671
4) Ввести доп. информацию "123456"
5) Нажать кнопку "отправить заявку"
act.res: кнопка исчезает и появляется
exp.res: сообщение "заявка отправлена"

**Comment by kulik** [comment]
fixed
