### ISSUE TITLE
(main bar) ввод недопустимых символов ";важность:средняя, срочность:обычная; симптомы:расхождение с требованиями;

### ISSUE THREAD

**Issue by oskar41** [TheAwesomeCompany/Bumperball#43]
Version: 1.0
Device: Windows 10, mozilla firefox v.45, resolution 1280x1024
Steps:
1) Open http://active.kh.ua
2) Нажать кнопку "играть в бампербол"
3) Ввести телефон №;%:
4) Ввести доп. информацию ""№%:%
5) Нажать кнопку "отправить заявку"
act.res: кнопка исчезает и появляется
exp.res: ошибка "не допустимые символы"

**Comment by kulik** [comment]
not  a bug
this is really allowed symbols for some of contacts data for example skype, email, etc.
