### ISSUE TITLE
(main bar) максимальное кол-во символов не ограничено ";важность:средняя, срочность:обычная; симптомы:расхождение с требованиями;

### ISSUE THREAD

**Issue by oskar41** [TheAwesomeCompany/Bumperball#44]
В полях телефона и доп. информации можно ввести неограниченое кол-во символов
Version: 1.0
Device: Windows 10, mozilla firefox v.45, resolution 1280x1024
Steps:
1) Open http://active.kh.ua
2) Нажать кнопку "играть в бампербол"
3) Ввести телефон 11111111111111111111111111111111111111111111111111111111111
4) Ввести доп. информацию 2222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222
5) Нажать кнопку "отправить заявку"
act.res: символы вводятся
exp.res: ограничение кол-ва символов

**Comment by kulik** [comment]
fixed

**Comment by kulik** [comment]
contacts limit 25
text limit 250
