### ISSUE TITLE
(main bar) не правильный адрес сайта";важность:средняя, срочность:обычная; симптомы:косметический дефект;

### ISSUE THREAD

**Issue by oskar41** [TheAwesomeCompany/Bumperball#45]
На основном экране сайта и в разделе наши контакты записан не верный адрес
Version: 1.0
Device: Windows 10, mozilla firefox v.45, resolution 1280x1024
Steps:
1) Open http://active.kh.ua
2) Проверить надпись сайта  в 'main bar" и "наши контакты"

act.res: info@active.kh.ua
exp.res: active.kh.ua

**Comment by kulik** [comment]
this is email adress so nothing wrong with that
