### ISSUE TITLE
(main bar) не работает функция "забронируй сейчас" и "связаться сейчас"; важность:критическая, срочность:высокая; симптомы: нереализованная функциональность;

### ISSUE THREAD

**Issue by oskar41** [TheAwesomeCompany/Bumperball#47]
Не возможно забронировать пакет 8-14 человек, 15-20 человек и 21-100+ человек
Version: 1.0
Device: Windows 10, mozilla firefox v.45, resolution 1280x1024
Steps:
1) Open http://active.kh.ua
2) Нажать кнопку "забронируй сейчас" напротив пакета друзья
3) Ввести телефон 380978834671
4) Ввести доп. информацию "123456"
5) Нажать кнопку "отправить заявку"
act.res: кнопка исчезает и появляется
exp.res: сообщение "заявка отправлена"

**Comment by kulik** [comment]
fixed
