### ISSUE TITLE
(Navigation bar) Некорректное отображение выпадающего окна (medium; normal)

### ISSUE THREAD

**Issue by Sergey-Saprikin** [TheAwesomeCompany/Bumperball#48]
В Navigation bar, при нажатии на кнопку в виде телефонной трубки, выпадающее окно появляется не под кнопкой, а в центре экрана
всегда (workaround: no)
Version: (1.0)
Разрешение экрана: (16:10; 1440 х 900)
Браузер: хром (49)
Steps: 
1) Открыть сайт: http://active.kh.ua
2) Нажать на кнопку в виде телефонной трубки
Expected result: окно выпадает под кнопкой
Actuale result: окно выпадает не под кнопкой
Symptom: cosmetic flaw; unexpected behavior
Attachment:
![222](https://cloud.githubusercontent.com/assets/17886282/13887243/b2744d02-ed4b-11e5-8332-d481d4fd9b1a.jpg)

**Comment by kulik** [comment]
fixed
