### ISSUE TITLE
(Пункт:"Часто задаваемые вопросы") Некорректное отображение  (medium; low)

### ISSUE THREAD

**Issue by Sergey-Saprikin** [TheAwesomeCompany/Bumperball#49]
Ответы в пункте "Часто задаваемые вопросы" располагаются не практично при данном разрешении экрана 
всегда (workaround: no)
Version: (1.0)
Разрешение экрана: (16:10; 1440 х 900)
Браузер: хром (49)
Steps: 
1) Открыть сайт: http://active.kh.ua
2) Нажать на кнопку в виде телефонной трубки
3) Навести на любой номер
Expected result: ответы располагаются в 2 стоблца
Actuale result: ответы идут сплошь 
Symptom: cosmetic flaw; unexpected behavior
Attachment:
![333](https://cloud.githubusercontent.com/assets/17886282/13887715/58bd20f6-ed4e-11e5-988f-ceddb29d59fd.jpg)
![444](https://cloud.githubusercontent.com/assets/17886282/13887750/8a543654-ed4e-11e5-822b-c3b9be1ac33d.jpg)

**Comment by kulik** [comment]
There is not just one width there is set of them

**Comment by kulik** [comment]
can't reproduce http://screencloud.net/v/oGnQ

**Comment by kulik** [comment]
fixed for 1600-1714 width
