### ISSUE TITLE
(меню)ссылка на контакты находится под логотипом

### ISSUE THREAD

**Issue by Tolstaya** [TheAwesomeCompany/Bumperball#5]
экран 1360*768
браузер Mozilla версия 45, Chrome 49

reproducibility: всегда
description: логотип "Бампербол" находится сверху ссылки на контакты
expected result : логотип находится рядом с ссылкой на контакты
actual result : логотип "Бампербол" находится сверху ссылки на контакты

**Comment by kulik** [comment]
Not good described. Have found what do you mention on 3rd reading.
