### ISSUE TITLE
Incorrect display page of the site after exit from window execution of an application (medium, normal)

### ISSUE THREAD

**Issue by dmitryklimenko** [TheAwesomeCompany/Bumperball#50]
Browser: Google Chrome 49.0
Version: 1.0

**Description:**
After user exit from the window "Оформить заявку", the site displayed incorrectly. The color of site window becomes darkened and all buttons can not be pressed. User is forced to reload the page.
**Reproducibility:** sometimes

**Actual Result:** After exit from the "Оформить заявку", site display darkened 
**Expection Result:** After user exiting from the "Оформить заявку", site is displayed as before
**STR:**
1). Open http://active.kh.ua/
2). Click "Играть в Бампербол"
3). Click on the "+" five times
4). Click on the darkened area around the window of execution of an application 

**Attachments:**
http://screencloud.net/v/975T
https://screencloud.net/v/v3Xf

**Comment by kulik** [comment]
What do you mean +

**Comment by dmitryklimenko** [comment]
I mean, after you exit the request form, the site should not be darkened (how displayed in screenshot).

**Comment by kulik** [comment]
can't reproduce
