### ISSUE TITLE
(Карта) Рвется/непонятен текст адреса (medium; normal)

### ISSUE THREAD

**Issue by Sergey-Saprikin** [TheAwesomeCompany/Bumperball#51]
В пункте "Где мы проводим игры", на карта, при нажатии на место проведения игр текст адреса непонятен
всегда (workaround: no)
Version: (1.0)
Разрешение экрана: (16:10; 1440 х 900)
Браузер: хром (49)
Steps: 
1) Открыть сайт: http://active.kh.ua
2) Нажать на один из адресов
Expected result: текст понятен
Actuale result: текст не понятен
Symptom: cosmetic flaw; unexpected behavior
![0000 lbx](https://cloud.githubusercontent.com/assets/17886282/13891083/1b61f68e-ed60-11e5-85df-485149ae1633.JPG)

Attachment:

**Comment by kulik** [comment]
This is google map behavior.
