### ISSUE TITLE
Navigation bar. При нажатии на пункт "КАРТА ПЛОЩАДОК", площадь окна карты открывается не в полном обьеме. (minor/low)

### ISSUE THREAD

**Issue by alino44ka** [TheAwesomeCompany/Bumperball#52]
При нажатии на пункт "КАРТА ПЛОЩАДОК", площадь окна карты открывается не в полном обьеме. Верхнюю часть закрывает навигатор бар.

Version 1.0
Device: браузер Chrome (48)
Steps:
- открыть сайт http://active.kh.ua/
- нажать в навигатор баре на пункт Карта площадок

Expected result: При нажатии на пункт "КАРТА ПЛОЩАДОК", площадь окна карты открывается в полном объеме и пользователь видит всю площадь окна карты
Actual resalt: При нажатии на пункт "КАРТА ПЛОЩАДОК", площадь окна карты открывается не в полном обьеме. Верхнюю часть закрывает навигатор бар.

**Comment by kulik** [comment]
http://screencloud.net/v/x2x6 What the problem?
