### ISSUE TITLE
В описании игры часто название игры "Бампербол" встречается написанное английскими буквами.(minor/low)

### ISSUE THREAD

**Issue by alino44ka** [TheAwesomeCompany/Bumperball#53]
На сайте часто встречается, что название игры написано английскими буквами (Bamperball), но оно должно быть написано всегда только русскими буквами
![aaac93dd1463772b1551b8ec089ed4fc](https://cloud.githubusercontent.com/assets/17886298/13893127/93a72a20-ed64-11e5-87c1-0d77b6eb8d85.png)
![153f5779ada2aaf666852249fab7f6e5](https://cloud.githubusercontent.com/assets/17886298/13893168/cc3dfb84-ed64-11e5-9b8e-b5c4e89a9c5d.png)

Version 1.0
Device: Браузер Chrome (48)

Steps:
- открыть сайт http://active.kh.ua/
- ознакомиться с описанием и правилами 

Expected result: Название игры Бампербол всегда наисано только на русскими буквами
Actual result: Название игры 4 раза встречается написанно е английскими буквами

**Comment by kulik** [comment]
fixed
