### ISSUE TITLE
Значек Viber должен находиться напротив номера телефона мобильного оператора КИЕВСТАР, а не отдельным номером (minor\low)

### ISSUE THREAD

**Issue by alino44ka** [TheAwesomeCompany/Bumperball#55]
Значек Viber должен находиться напротив номера телефона мобильного оператора КИЕВСТАР, а не отдельным номером, т.к. вайбер привязан к номеру, а не является отдельным мобильным оператором 
Version: 1.0
Device: Браузер Chrome (48)
Steps:
- Открыть сайт: http://active.kh.ua/
- В навигатор баре нажать последний значек Телефонная трубка

Expected result: Значек Viber должен находиться напротив номера телефона мобильного оператора КИЕВСТАР, а не отдельным номером, т.к. вайбер привязан к номеру, а не является отдельным мобильным оператором 
Actual result: Значек Viber с номером мобильного оператора киевстар находится на отдельной строке

**Comment by kulik** [comment]
as desiigned, not a bug
