### ISSUE TITLE
В меню Стоимость в тексте есть опечатка,орфографические ошибки . (minor,normal)

### ISSUE THREAD

**Issue by Valeri1788** [TheAwesomeCompany/Bumperball#56]
Description:
Version:1.0
Device:Mozilla Firefox
В меню Стоимость в тексте есть опечатка 
 ,,Мы проводим мероприятие там где Вам удобно. Все будет приготовлено к игре, когда вы приедете. Му готовы организовать Игру в более чем 200 местах в Вашем городе." Опечатка в слове ,,My" написано на английском языке, и орфографическая ошибка слова ,,Игру" написано с большой буквы.
Steps:
1.Открыть сайт active.kh.ua
2.Нажать на меню ,,Стоимость"
Expected result:,,# **Мы** готовы организовать игру , чем 200 местах в Вашем городе"
Actual result:  ,, **My** готовы организовать Игру чем 200 местах в Вашем городе."
Reproducibility:always.
Symptom: сosmetic flaw.

**Comment by kulik** [comment]
fixed
