### ISSUE TITLE
(Top bar)Не работает функция звонить; major; high;

### ISSUE THREAD

**Issue by oskar41** [TheAwesomeCompany/Bumperball#57]
OS:  iOS 7.0
Browser:SAFARI
Device: ipad mini / Apple A7 (1.3 ГГц) / RAM 1 ГБ 
Screen resolution: 2048 x 1536
Diagonal: 7.9"
Режим отображения: портретный
Version: 1.0

Steps:
1) Open http://active.kh.ua
2) Нажать кнопку телефонной трубки в правом верхнем углу
3) Выбрать номер МТС
4) Нажать "call" во всплывающем окне
act.res: всплывающее окно исчезает
exp.res: происходит звонок по выбраному номеру

**Comment by kulik** [comment]
can't reproduce
