### ISSUE TITLE
Test QA - При нажатии на иконку электронный адрес

### ISSUE THREAD

**Issue by Anatoliy-G** [TheAwesomeCompany/Bumperball#58]
При нажатии на иконку электронный адрес
Device: MacBook, Экран 13" (1280 x 800) XP - http://c2n.me/3w5EXP5
Положение экрана - Альбомное 
Steps:
1) Open http://active.kh.ua
2) Нажать нажатии на иконку электронный адрес, в низу сайта
Не запускается почтовая программа (Outlook Express, стоит на компе по умолчанию)
http://c2n.me/3w5ErOS

**Comment by oskar41** [comment]
same

OS:  iOS 7.0
Browser:SAFARI
Device: ipad mini / Apple A7 (1.3 ГГц) / RAM 1 ГБ 
Screen resolution: 2048 x 1536
Diagonal: 7.9"
Режим отображения: портретный
Version: 1.0

**Comment by alino44ka** [comment]
В Navigatoir Bar в меню Контакты при нажатии на кнопку электронной почты, не предлагается на выбор приложения электронной почты для отправки письма. 
OS: iOS/windows
Device: 
ipad 7"9/1024х780
iphone 4"/1136х640
HTC 4"inch/480х800
Expected result: В Navigatoir Bar в меню Контакты при нажатии на кнопку электронной почты, предлагается на выбор приложения электронной почты для отправки письма. 
Actual result: В Navigatoir Bar в меню Контакты при нажатии на кнопку электронной почты, не предлагается на выбор приложения электронной почты для отправки письма.

**Comment by kulik** [comment]
specific device, iPAd issue
