### ISSUE TITLE
(mobile) Не работает перелистка пакетов (minor; low)

### ISSUE THREAD

**Issue by dmitryklimenko** [TheAwesomeCompany/Bumperball#59]
OS: Andriod
Browser: Opera
Device: Prestigio 4055
Screen resolution: 480 x 800
Diagonal: 4"
Режим отображения: портретный
Version: 1.0

Description:
В мобильной версии сайта изначально отображается только один из трех доступных для заказа пакетов. При попытке выбрать просмотр других пакетов с помощью нажатия на круглую маленькую кнопку, которая находится под описанием пакета, страница перезагружается и возвращается в то же положение, что и до перезагрузки. 

Actual Result: После нажатия на выбор другого пакета, страница перезагружается и отображается всё тот же пакет.
Expection Result: После нажатия на выбор другого пакета, страница перезагружается и отображается выбранный по счету пакет.
STR:
1). Открыть http://active.kh.ua/
2). Отмотать в раздел "Стоимость"
3). Нажать на средний кружок под описанием пакета.

Attachments:

**Comment by kulik** [comment]
can't reproduce
