### ISSUE TITLE
(Uncorrect video play) Uncorrect video play (minor; low) (Mobile device)

### ISSUE THREAD

**Issue by Sergey-Saprikin** [TheAwesomeCompany/Bumperball#60]
There are uncorrect video play on portrait orientation on main page of site (workaround: no)
Version: (1.0)
Device: Lenovo A6000 (diagonal: 5; resolution:1366 х 768)
Browser: Chrome (49)
Version of device: Android 4
Steps: 
1) Open site: http://active.kh.ua
2) Click on play video buttom
3) Look at Main page with video
Expected result: Video display correct
Actuale result: Video displaypartially
Symptom: cosmetic flaw, unexpected behavior
Attachment:
![screenshot_2016-03-26-11-57-10](https://cloud.githubusercontent.com/assets/17886282/14059520/d41d49bc-f34b-11e5-8548-8fe2ea0879a7.png)

**Comment by kulik** [comment]
not so important
