### ISSUE TITLE
(mobile) Некорректное отображение новостных лент соцсетей (medium, normal)

### ISSUE THREAD

**Issue by dmitryklimenko** [TheAwesomeCompany/Bumperball#62]
OS: Andriod
Browser: Opera
Device: Prestigio 4055
Screen resolution: 480 x 800
Режим отображения: портретный
Diagonal: 4"
Version: 1.0

Description:
В мобильной версии сайта некорректно отображается раздел "Добавляйтесь к нам в соцсетях, чтобы быть в курсе об акциях и скидках". Элементы новостной ленты накладываются на раздел "Часто задаваемые вопросы".

Actual Result: Разделы налезают друг на друга
Expection Result: Разделы не налезают друг на друга

STR:
1). Открыть http://active.kh.ua/
2). Отмотать в раздел "Добавляйтесь к нам в соцсетях, чтобы быть в курсе об акциях и скидках"

Attachments:

**Comment by Ksiu-Sliusarova** [comment]
На телефоне HTC 8S (Windows 8, 4", 480 x 800) текст в новостной ленте вылазит за свои рамки.
![wp_ss_20160326_0007](https://cloud.githubusercontent.com/assets/17857636/14079186/8e734fa0-f504-11e5-8ee4-b4e4da4f367d.png)

**Comment by kulik** [comment]
this is 3rd party API
