### ISSUE TITLE
(main bar) не воспроизводится видео; major; high;

### ISSUE THREAD

**Issue by oskar41** [TheAwesomeCompany/Bumperball#63]
OS:  iOS 7.0
Browser:SAFARI
Device: ipad mini / Apple A7 (1.3 ГГц) / RAM 1 ГБ 
Screen resolution: 2048 x 153
Diagonal: 7.9"
Режим отображения: портретный
Version: 1.0

Steps:
1) Open http://active.kh.ua
2) Нажать на фото в верхнем экране

act.res: видна только картинка
exp.res: воспроизводится видео

**Comment by kulik** [comment]
fixed
