### ISSUE TITLE
(Main page) Uncorrect display of item "ЗВОНИ" (minor; low) (Mobile device)

### ISSUE THREAD

**Issue by Sergey-Saprikin** [TheAwesomeCompany/Bumperball#64]
There are uncorrect display of item "ЗВОНИ" on gorizontal orientation on main page of site (workaround: no)
Version: (1.0)
Device: Lenovo A6000 (diagonal: 5; resolution:1366 х 768)
Browser: Chrome (49)
Version of device: Android 4
Steps: 
1) Open site: http://active.kh.ua
2) Tern the device to gorizontal orientation
3) Look at Main page on item "ЗВОНИ"
Expected result: Item on his place
Actuale result: Item "ЗВОНИ" overrides other items of interfase
Symptom: cosmetic flaw, unexpected behavior
Attachment:
![screenshot_2016-03-26-12-20-59](https://cloud.githubusercontent.com/assets/17886282/14059561/901a5df2-f34d-11e5-8036-377db06b5502.png)

**Comment by oskar41** [comment]
same

OS: Android 4.4 KitKat
Browser:Chrome
Device: ASUS MeMO Pad 8 (ME181C), Intel Atom Z3745, 1 ГБ RAM
Screen resolution: 1280 х 800
Diagonal: 8"
Режим отображения: портретный
Version: 1.0

**Comment by kulik** [comment]
fixed
