### ISSUE TITLE
Test QA - размер 3 блока не соответствует 1 и 2 (вертикаль)

### ISSUE THREAD

**Issue by Anatoliy-G** [TheAwesomeCompany/Bumperball#65]
Размер  3 блока не соответствует 1 и 2
Device: MacBook, Экран 13" (1280 x 800) XP - http://c2n.me/3w5EXP5
Положение экрана - Альбомное 
Steps:
1) Open http://active.kh.ua
Actual Result: Размер 3 блока (вертикаль) меньше 1 и 2
Expection Result: Размер каждого блока одинаков
http://c2n.me/3w5GPuL - 3 блок вертикаль (не корректна)
http://c2n.me/3w5HeFh - 2 блок и 1 блок идентичны (вертикаль)

**Comment by kulik** [comment]
fixed
