### ISSUE TITLE
(mobile) Некорректно отображается форма заявки (major; high)

### ISSUE THREAD

**Issue by dmitryklimenko** [TheAwesomeCompany/Bumperball#67]
OS: Andriod
Browser: Opera
Device: Prestigio 4055
Screen resolution: 480 x 800
Diagonal: 4"
Режим отображения: портретный
Version: 1.0

Description:
В мобильной версии сайта некорректно отображается форма заполнения заявки. Слова "Телефон" и "Дополнительная информация" перекрывают слова "Телефон, скайп и т.д." (см. приложение)

Actual Result: Лейблы перекрывают друг друга
Expection Result: Лейблы не перекрывают друг друга
STR:
1). Открыть http://active.kh.ua/
2). Нажать на "Играть в бампербол"

Attachments:

**Comment by Sergey-Saprikin** [comment]
The same problem on device with characteristics:
Device: Lenovo A6000 (diagonal: 5; resolution:1366 х 768)
Browser: Chrome (49)
Version of device: Android 4
![screenshot_2016-03-26-12-50-42](https://cloud.githubusercontent.com/assets/17886282/14059670/86bcc980-f351-11e5-8f20-e770aa8b7595.png)

**Comment by Ksiu-Sliusarova** [comment]
На телефоне HTC 8S (Windows 8, 4", 480 x 800) после нажатия "Играть в бампербол" на экране либо совсем не появляется форма заявки (вместо этого на экране кусок картинки-заставки), либо появляется после простого скролинга, отображаясь некорректно. При этом сайт иногда сам перебрасывает между началом и концом сайта, а кнопка "Отправить" не срабатывает. Очень странное поведение сайта. См. скриншоты.

![wp_ss_20160326_0003](https://cloud.githubusercontent.com/assets/17857636/14079094/d14d4dea-f503-11e5-8c07-3ae9abb241ee.png)
![wp_ss_20160326_0004](https://cloud.githubusercontent.com/assets/17857636/14079095/d14d8f58-f503-11e5-847b-bc71d49309df.png)
![wp_ss_20160326_0005](https://cloud.githubusercontent.com/assets/17857636/14079097/d14e95c4-f503-11e5-8e19-ca1d76e006c6.png)
![wp_ss_20160326_0006](https://cloud.githubusercontent.com/assets/17857636/14079096/d14e3e80-f503-11e5-8687-766af7a97c98.png)

**Comment by kulik** [comment]
unfortunately we doesn't support this device/ browser
