### ISSUE TITLE
(Social networks) following a link is`n work (medium; normal) (Mobile device)

### ISSUE THREAD

**Issue by Sergey-Saprikin** [TheAwesomeCompany/Bumperball#68]
The following a link "VK" isn work when you click it (workaround: no)
Version: (1.0)
Device: Lenovo A6000 (diagonal: 5; resolution:1366 х 768)
Browser: Chrome (49)
Version of device: Android 4
Steps: 
1) Open site: http://active.kh.ua
2) Click on dropdown list in upper left corner of the site
3) Click "VK"
Expected result: The following is successful
Actuale result: The following isn`t work
Symptom: missing feature
Attachment:
[screenshot_2016-03-26-12-33-33](https://cloud.githubusercontent.com/assets/17886282/14059625/880e9d42-f34f-11e5-800e-c01723147419.png)

**Comment by kulik** [comment]
just redirection on VK group designed
