### ISSUE TITLE
(mobile) top bar не отображается (major, high)

### ISSUE THREAD

**Issue by DimaKudin** [TheAwesomeCompany/Bumperball#69]
OS: Andriod
Device: samsung gt-s5660
Screen resolution: 320х480
Режим отображения: портретный
Diagonal: 3.2"
Version: 1.0

Description:
В мобильной версии сайта не отображается top bar 

Actual Result: top bar не отображается 
Expection Result: top bar активен

STR:
1). Открыть http://active.kh.ua/

Attachments:

**Comment by Ksiu-Sliusarova** [comment]
Not clear. Add screen shot please.
