### ISSUE TITLE
(main bar, contact bar) Маленькая область нажатия кнопок (minor; low)

### ISSUE THREAD

**Issue by oskar41** [TheAwesomeCompany/Bumperball#70]
OS: iOS 7.0
Browser:SAFARI
Device: ipad mini / Apple A7 (1.3 ГГц) / RAM 1 ГБ
Screen resolution: 2048 x 1536
Diagonal: 7.9"
Режим отображения: портретный
Version: 1.0

Description:
Плохой отклик при нажатии на кнопки "играть в бампербол", "Бампербол", кнопки "меню" в левом верхнемп экране изза маленькой области нажатия.

Actual Result: Иногда приходится нажимать несколько раз
Expection Result: Отличный отклик при нажатии
STR:
1). Открыть http://active.kh.ua/
2). Нажать "играть в бампербол"

**Comment by kulik** [comment]
this button designed by guidelines
