### ISSUE TITLE
(main bar)Нет кнопки воспроизведения видео в альбомном режиме.major; high.

### ISSUE THREAD

**Issue by OlgaGushchina** [TheAwesomeCompany/Bumperball#72]
OS: Android 5.0 (Lollipop)
Browser: Chrome (49)
Device: Xiaomi Redmi Note 2 
Screen resolution: 1080 x 1920 
Diagonal: 5,5"
Режим отображения:альбомный
Version: 1.0

Description:
В альбомном режиме нет кнопки воспроизведения видео.Видео не воспроизводится(см.скрин 1)
Actual Result:Нет кнопки воспроизведения, видео не воспроизводится
Expection Result: Видео воспроизводится при нажатии на кнопку воспроизведения.
STR:
1). Открыть http://active.kh.ua/
2). Перейти в альбомный режим.
![screenshot_2016-03-26-18-10-49_com android chrome](https://cloud.githubusercontent.com/assets/17857626/14076247/bfb88fd8-f4e8-11e5-8ebc-5ba10a539bc0.png)

**Comment by kulik** [comment]
fixed
