### ISSUE TITLE
Неподходящий размер иконки Instagram (меню)

### ISSUE THREAD

**Issue by dmitryklimenko** [TheAwesomeCompany/Bumperball#8]
Browser: Google Chrome 49.0
Version: 1.0

Description:
При открытии страницы сайта мы видим, что иконка социальной сети Instagram по размерам меньше, чем иконки соцсетей ВКонтакте и Facebook
Actual Result: Размер иконки Instagram равен 35х33
Expection Result: Размер иконки Instagram равен 35х35
STR: 
1). Открыть сайт http://active.kh.ua/

Comments: http://i9.pixs.ru/storage/9/0/0/425png_4570144_21119900.png

**Comment by kulik** [comment]
not so important from my point, but it is real cosmetic bug
